/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f2a395a48ce1d65484d5358226108f7e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		DISCORD_WEBHOOK_URL: string;
		T212_API_KEY: string;
		T212_API_SECRET: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DISCORD_WEBHOOK_URL" | "T212_API_KEY" | "T212_API_SECRET">> {}
}
