/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 653728295532008db4485f36c8f4a16f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		DISCORD_WEBHOOK_URL: string;
		T212_API_KEY: string;
		T212_API_SECRET: string;
		GOOGLE_MAPS_API_KEY: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DISCORD_WEBHOOK_URL" | "T212_API_KEY" | "T212_API_SECRET" | "GOOGLE_MAPS_API_KEY">> {}
}
